var mysql = require('mysql');
var conn = require('../model/db');
var conn_obj = conn.db();

/* IN ORDER TO HAVE A UNIVERSAL CONNETION SCRIPT FOR ALL MY CLASS BUILDS THE REQUIRE A DATABASE I CREATED AN EXPORT METHOD OUTSIDE OF THE CLASS-PROJECT FOLDER THAT CONTAINS MY DATABASE CONNECTION INFORMATION.  THE FOLLOWING CODE REQUIRES THAT MODULE AND RETURNS THE OBJECT CONTAINING MY CONNECTION INFORMATION */
exports.connect = function(){
	var pool = mysql.createPool(conn_obj);
	return pool;
};