var numbers = new Buffer("123456789");
console.log();
console.log(numbers.toString());
console.log();
var slice = numbers.slice(3, 6);
console.log(slice.toString());
slice[0] = '#'.charCodeAt(0);
slice[slice.length - 1] = '#'.charCodeAt(0);
console.log();
console.log(slice.toString());
console.log();
console.log(numbers.toString());